---
title: "R Notebook"
output: html_notebook
---



```{r}
library(tidyverse)
library(janitor)
library(lubridate)
library(zoo)
library(ggplot2)
library(tsibble)


admin_hb_speciality <- read_csv("raw_data/hospital_admissions_hb_specialty_20221102.csv")

```

```{r}
#start cleaning. Dates from 20200105 to 20221023

admin_hb_speciality <- admin_hb_speciality %>% clean_names()



```

```{r}
# Delete columns : HBFQ - NA/ d , admission_type_qf : NA, specialty_qf : NA

admin_hb_speciality <- admin_hb_speciality %>% 
  select(-c(3,5,7))

view(admin_hb_speciality)
```

```{r}
#Change column  'hb' to 'healthboard'
admin_hb_speciality <- admin_hb_speciality %>% 
  rename(hb = hb) %>%
  mutate(hb = recode(hb,
                     "S08000015" = "NHS Ayrshire and Arran",
                     "S08000016" = "NHS Borders",
                     "S08000017" = "NHS Dumfries and Galloway",
                     "S08000019" = "NHS Forth Valley",
                     "S08000020" = "NHS Grampian",
                     "S08000022" = "NHS Highland",
                     "S08000024" = "NHS Lothian",
                     "S08000025" = "NHS Orkney",
                     "S08000026" = "NHS Shetland",
                     "S08000028" = "NHS Western Isles",
                     "S08000029" = "NHS Fife",
                     "S08000030" = "NHS Tayside",
                     "S08000031" = "NHS Greater Glasgow and Clyde",
                     "S08000032" = "NHS Lanarkshire",
                     "S92000003" = "Scotland",
                     "SB0801"    = "The Golden Jubille National",
                     "S08000018" = "NHS Fife",
"S08000021" = "NHS Greater Glasgow and Clyde",
"S08000023" = "NHS Lanarkshire",
"S08000027" = "NHS Tayside"))
  
view(admin_hb_speciality)
```

```{r}
# modify date
admin_hb_speciality <-  admin_hb_speciality %>% 
  mutate(week_ending = ymd(week_ending),
         month_enter = month(week_ending, label = TRUE, abbr = FALSE),
         year_enter = year(week_ending),
         day_enter = day(week_ending),
         )


```


```{r}
admin_hb_speciality <- admin_hb_speciality %>% 
  mutate(quarters = case_when(
         month_enter %in% c('January','February','March')~ "Q1",
         month_enter %in% c('April','May', 'June') ~ "Q2",
         month_enter %in% c('July','August','September') ~ "Q3",
         month_enter %in% c('October', 'November', 'December')~ "Q4",
         ))
view(admin_hb_speciality)


```



       AVERAGE KIDS BY HEALTHBOARD 20-22 IN Quartes
Q1

<!-- ```{r} -->
<!-- #2020 -->
<!-- mean_kids_2020_q1 <- admin_hb_speciality %>%  -->
<!--   select(year_enter, month_enter,day_enter,quarters, number_admissions,specialty,hb) %>%  -->
<!--   group_by(hb) %>%  -->
<!--   filter(year_enter == '2020') %>%  -->
<!--   filter(specialty %in% c('Paediatrics (medical & surgical)','Paediatrics (medical)')) %>%  -->
<!--   filter(quarters == "Q1") %>%  -->
<!--   filter(hb != 'Scotland') %>% -->
<!--   summarise(mean_kids = mean(number_admissions)) %>%  -->
<!--   arrange(desc(mean_kids)) -->

<!-- mean_kids_2020_q1 -->
<!-- ``` -->


<!-- ```{r} -->
<!-- #Plot kids 2020 January_march -->
<!-- mean_kids_2020_q1%>%  -->
<!-- ggplot(aes(x= mean_kids, y = hb ))+ -->
<!--   geom_point() -->

<!-- ``` -->


<!-- ```{r} -->
<!-- #2021. Number of admission decrease during the first months 2021 from year before and year after -->

<!-- mean_kids_2021_q1 <- admin_hb_speciality %>%  -->
<!--   select(year_enter, month_enter,day_enter,quarters, number_admissions,specialty,hb) %>%  -->
<!--   group_by(hb) %>%  -->
<!--   filter(year_enter == '2021') %>%  -->
<!--   filter(specialty %in% c('Paediatrics (medical & surgical)','Paediatrics (medical)')) %>%  -->
<!--   filter(quarters == "Q1") %>%  -->
<!--   filter(hb != 'Scotland') %>% -->
<!--   summarise(mean_kids = mean(number_admissions)) %>%  -->
<!--   arrange(desc(mean_kids)) -->



<!-- mean_kids_2021_q1 -->
<!-- ``` -->


<!-- ```{r} -->
<!-- #Plot kids 2021 January_march -->
<!-- mean_kids_2021_q1%>%  -->
<!-- ggplot(aes(x= mean_kids, y = hb ))+ -->
<!--   geom_point() -->

<!-- ``` -->

<!-- ```{r} -->

<!-- #2022 -->
<!--  mean_kids_2022_q1 <- admin_hb_speciality %>%  -->
<!--   select(year_enter, month_enter,day_enter,quarters, number_admissions,specialty,hb) %>%  -->
<!--   group_by(hb) %>%  -->
<!--   filter(year_enter == '2022') %>%  -->
<!--   filter(specialty %in% c('Paediatrics (medical & surgical)','Paediatrics (medical)')) %>%  -->
<!--   filter(quarters == "Q1") %>%  -->
<!--   filter(hb != 'Scotland') %>% -->
<!--   summarise(mean_kids = mean(number_admissions)) %>%  -->
<!--   arrange(desc(mean_kids)) -->

<!-- mean_kids_2022_q1 -->
<!-- ``` -->

<!-- ```{r} -->
<!-- mean_kids_2022_q1%>%  -->
<!-- ggplot(aes(x= mean_kids, y = hb ))+ -->
<!--   geom_point() -->

<!-- ``` -->
<!-- Q2 -->
<!-- ```{r} -->
<!-- mean_kids_2020_q2 <- admin_hb_speciality %>%  -->
<!--   select(year_enter, month_enter,day_enter,quarters, number_admissions,specialty,hb) %>%  -->
<!--   group_by(hb) %>%  -->
<!--   filter(year_enter == '2020') %>%  -->
<!--   filter(specialty %in% c('Paediatrics (medical & surgical)','Paediatrics (medical)')) %>%  -->
<!--   filter(quarters == "Q2") %>%  -->
<!--   filter(hb != 'Scotland') %>% -->
<!--   summarise(mean_kids = mean(number_admissions)) %>%  -->
<!--   arrange(desc(mean_kids)) -->

<!-- mean_kids_2020_q2 -->
<!-- ``` -->
<!-- ```{r} -->
<!-- mean_kids_2020_q2%>%  -->
<!-- ggplot(aes(x= mean_kids, y = hb ))+ -->
<!--   geom_point() -->

<!-- ``` -->
<!-- ```{r} -->
<!-- mean_kids_2021_q2 <- admin_hb_speciality %>%  -->
<!--   select(year_enter, month_enter,day_enter,quarters, number_admissions,specialty,hb) %>%  -->
<!--   group_by(hb) %>%  -->
<!--   filter(year_enter == '2021') %>%  -->
<!--   filter(specialty %in% c('Paediatrics (medical & surgical)','Paediatrics (medical)')) %>%  -->
<!--   filter(quarters == "Q2") %>%  -->
<!--   filter(hb != 'Scotland') %>% -->
<!--   summarise(mean_kids = mean(number_admissions)) %>%  -->
<!--   arrange(desc(mean_kids)) -->

<!-- mean_kids_2021_q2 -->
<!-- ``` -->


<!-- ```{r} -->
<!-- mean_kids_2021_q2%>%  -->
<!-- ggplot(aes(x= mean_kids, y = hb ))+ -->
<!--   geom_point() -->
<!-- ``` -->


<!-- ```{r} -->
<!-- mean_kids_2022_q2 <- admin_hb_speciality %>%  -->
<!--   select(year_enter, month_enter,day_enter,quarters, number_admissions,specialty,hb) %>%  -->
<!--   group_by(hb) %>%  -->
<!--   filter(year_enter == '2022') %>%  -->
<!--   filter(specialty %in% c('Paediatrics (medical & surgical)','Paediatrics (medical)')) %>%  -->
<!--   filter(quarters == "Q2") %>%  -->
<!--   filter(hb != 'Scotland') %>% -->
<!--   summarise(mean_kids = mean(number_admissions)) %>%  -->
<!--   arrange(desc(mean_kids)) -->

<!-- mean_kids_2022_q2 -->
<!-- ``` -->

<!-- ```{r} -->
<!-- mean_kids_2022_q2%>%  -->
<!-- ggplot(aes(x= mean_kids, y = hb))+ -->
<!--   geom_point() -->
<!-- ``` -->
<!--    Q3 -->
<!-- ```{r} -->
<!-- mean_kids_2020_q3 <- admin_hb_speciality %>%  -->
<!--   select(year_enter, month_enter,day_enter,quarters, number_admissions,specialty,hb) %>%  -->
<!--   group_by(hb) %>%  -->
<!--   filter(year_enter == '2020') %>%  -->
<!--   filter(specialty %in% c('Paediatrics (medical & surgical)','Paediatrics (medical)')) %>%  -->
<!--   filter(quarters == "Q3") %>%  -->
<!--   filter(hb!= 'Scotland') %>% -->
<!--   summarise(mean_kids = mean(number_admissions)) %>%  -->
<!--   arrange(desc(mean_kids)) -->

<!-- mean_kids_2020_q3 -->
<!-- ``` -->

<!-- ```{r} -->
<!-- mean_kids_2020_q3%>%  -->
<!-- ggplot(aes(x= mean_kids, y = hb ))+ -->
<!--   geom_point() -->

<!-- ``` -->
<!-- ```{r} -->
<!-- mean_kids_2021_q3 <- admin_hb_speciality %>%  -->
<!--   select(year_enter, month_enter,day_enter,quarters, number_admissions,specialty,hb) %>%  -->
<!--   group_by(hb) %>%  -->
<!--   filter(year_enter == '2021') %>%  -->
<!--   filter(specialty %in% c('Paediatrics (medical & surgical)','Paediatrics (medical)')) %>%  -->
<!--   filter(quarters == "Q3") %>%  -->
<!--   filter(hb != 'Scotland') %>% -->
<!--   summarise(mean_kids = mean(number_admissions)) %>%  -->
<!--   arrange(desc(mean_kids)) -->

<!-- mean_kids_2020_q3 -->
<!-- ``` -->

<!-- ```{r} -->
<!-- mean_kids_2021_q3%>%  -->
<!-- ggplot(aes(x= mean_kids, y = hb ))+ -->
<!--   geom_point() -->
<!-- ``` -->
<!-- ```{r} -->
<!-- mean_kids_2022_q3 <- admin_hb_speciality %>%  -->
<!--   select(year_enter, month_enter,day_enter,quarters, number_admissions,specialty,hb) %>%  -->
<!--   group_by(hb) %>%  -->
<!--   filter(year_enter == '2022') %>%  -->
<!--   filter(specialty %in% c('Paediatrics (medical & surgical)','Paediatrics (medical)')) %>%  -->
<!--   filter(quarters == "Q3") %>%  -->
<!--   filter(hb != 'Scotland') %>% -->
<!--   summarise(mean_kids = mean(number_admissions)) %>%  -->
<!--   arrange(desc(mean_kids)) -->

<!-- mean_kids_2022_q3 -->
<!-- ``` -->

<!-- ```{r} -->
<!-- mean_kids_2022_q3%>%  -->
<!-- ggplot(aes(x= mean_kids, y = hb ))+ -->
<!--   geom_point() -->
<!-- ``` -->

<!-- Q4 -->

<!-- ```{r} -->
<!-- mean_kids_2020_q4 <- admin_hb_speciality %>%  -->
<!--   select(year_enter, month_enter,day_enter,quarters, number_admissions,specialty,hb) %>%  -->
<!--   group_by(hb) %>%  -->
<!--   filter(year_enter == '2020') %>%  -->
<!--   filter(specialty %in% c('Paediatrics (medical & surgical)','Paediatrics (medical)')) %>%  -->
<!--   filter(quarters == "Q4") %>%  -->
<!--   filter(hb != 'Scotland') %>% -->
<!--   summarise(mean_kids = mean(number_admissions)) %>%  -->
<!--   arrange(desc(mean_kids)) -->

<!-- mean_kids_2020_q4 -->
<!-- ``` -->

<!-- ```{r} -->
<!-- mean_kids_2020_q4%>%  -->
<!-- ggplot(aes(x= mean_kids, y = hb ))+ -->
<!--   geom_point() -->
<!-- ``` -->

<!-- ```{r} -->
<!-- mean_kids_2021_q4 <- admin_hb_speciality %>%  -->
<!--   select(year_enter, month_enter,day_enter,quarters, number_admissions,specialty,hb) %>%  -->
<!--   group_by(hb) %>%  -->
<!--   filter(year_enter == '2021') %>%  -->
<!--   filter(specialty %in% c('Paediatrics (medical & surgical)','Paediatrics (medical)')) %>%  -->
<!--   filter(quarters == "Q4") %>%  -->
<!--   filter(hb != 'Scotland') %>% -->
<!--   summarise(mean_kids = mean(number_admissions)) %>%  -->
<!--   arrange(desc(mean_kids)) -->

<!-- mean_kids_2021_q4 -->
<!-- ``` -->

<!-- ```{r} -->
<!-- mean_kids_2021_q4%>%  -->
<!-- ggplot(aes(x= mean_kids, y = hb ))+ -->
<!--   geom_point() -->
<!-- ``` -->

<!-- ```{r} -->

<!-- mean_kids_2022_q4 <- admin_hb_speciality %>%  -->
<!--   select(year_enter, month_enter,day_enter,quarters, number_admissions,specialty,hb) %>%  -->
<!--   group_by(hb) %>%  -->
<!--   filter(year_enter == '2022') %>%  -->
<!--   filter(specialty %in% c('Paediatrics (medical & surgical)','Paediatrics (medical)')) %>%  -->
<!--   filter(quarters == "Q4") %>%  -->
<!--   filter(hb != 'Scotland') %>% -->
<!--   summarise(mean_kids = mean(number_admissions)) %>%  -->
<!--   arrange(desc(mean_kids)) -->

<!-- mean_kids_2022_q4 -->
<!-- ``` -->
<!-- ```{r} -->
<!-- mean_kids_2022_q4%>%  -->
<!-- ggplot(aes(x= mean_kids, y = hb ))+ -->
<!--   geom_point() -->
<!-- ``` -->

   BY YEARS  2020

```{r}
yearly_mean_kids_2020 <- admin_hb_speciality %>% 
  select(year_enter, month_enter,quarters, number_admissions,specialty,hb) %>% 
  group_by(hb) %>% 
  filter(year_enter == '2020') %>% 
  filter(specialty %in% c('Paediatrics (medical & surgical)','Paediatrics (medical)')) %>% 
  #filter(quarters == "Q4") %>% 
  filter(hb != 'Scotland') %>%
  summarise(mean_kids = mean(number_admissions)) %>% 
  arrange(desc(mean_kids))

yearly_mean_kids_2020
```

```{r}
yearly_mean_kids_2020%>% 
ggplot(aes(x= mean_kids, y = hb))+
  geom_point()+
  labs(
    title = "2020 mean Kids Number Admission by Healthboard",
    x = "mean number",
    y = "Healthboard"
  )
```

2021


```{r}
yearly_mean_kids_2021 <- admin_hb_speciality %>% 
  select(year_enter, month_enter,quarters, number_admissions,specialty,hb) %>% 
  group_by(hb) %>% 
  filter(year_enter == '2021') %>% 
  filter(specialty %in% c('Paediatrics (medical & surgical)','Paediatrics (medical)')) %>% 
  #filter(quarters == "Q4") %>% 
  filter(hb != 'Scotland') %>%
  summarise(mean_kids = mean(number_admissions)) %>% 
  arrange(desc(mean_kids))

yearly_mean_kids_2021
```
```{r}
yearly_mean_kids_2021%>% 
ggplot(aes(x= mean_kids, y = hb))+
  geom_point()+
  labs(
    title = "2021 mean Kids Number Admission by Healthboard",
    x = "mean number",
    y = "Healthboard"
  )
```
```{r}
yearly_mean_kids_2022<- admin_hb_speciality %>% 
  select(year_enter, month_enter,quarters, number_admissions,specialty,hb) %>% 
  group_by(hb) %>% 
  filter(year_enter == '2022') %>% 
  filter(specialty %in% c('Paediatrics (medical & surgical)','Paediatrics (medical)')) %>% 
  #filter(quarters == "Q4") %>% 
  filter(hb != 'Scotland') %>%
  summarise(mean_kids = mean(number_admissions)) %>% 
  arrange(desc(mean_kids))

yearly_mean_kids_2022
```

```{r}
yearly_mean_kids_2022%>% 
ggplot(aes(x= mean_kids, y = hb ))+
  geom_point()+
  labs(
    title = "2022 mean Kids Number Admission by Healthboard",
    x = "mean number",
    y = "Healthboard"
  )
```

```{r}
mean_kids_three_years <- admin_hb_speciality %>% 
  select(year_enter, month_enter,quarters,quarters, number_admissions,specialty,hb) %>% 
  group_by(hb) %>% 
  #filter(year_enter == '2022') %>% 
  filter(specialty %in% c('Paediatrics (medical & surgical)','Paediatrics (medical)')) %>% 
  #filter(quarters == "Q4") %>% 
  filter(hb != 'Scotland') %>%
  summarise(mean_kids = mean(number_admissions)) %>% 
  arrange(desc(mean_kids))

mean_kids_three_years
```
```{r}
yearly_mean_kids_2022%>% 
ggplot(aes(x= mean_kids, y = hb ))+
  geom_point()
```

```{r}
#Mean Glasgow in three years
admin_hb_speciality %>% 
  select(year_enter, month_enter,quarters,quarters, number_admissions,specialty,hb) %>% 
  group_by(hb) %>% 
  #filter(year_enter == '2022') %>% 
  filter(specialty %in% c('Paediatrics (medical & surgical)','Paediatrics (medical)')) %>% 
  #filter(quarters == "Q4") %>% 
  filter(hb == "NHS Greater Glasgow and Clyde" ) %>% 
  #filter(healthboard != 'Scotland') %>%
  summarise(mean_kids = mean(number_admissions)) %>% 
  arrange(desc(mean_kids))
```
```{r}
#three years scotland

admin_hb_speciality %>% 
  select(year_enter, month_enter,quarters, number_admissions,specialty,hb) %>% 
  group_by(hb) %>% 
  #filter(year_enter == '2022') %>% 
  filter(specialty %in% c('Paediatrics (medical & surgical)','Paediatrics (medical)')) %>% 
  #filter(quarters == == 'Scotland') %>%
  summarise(mean_kids = mean(number_admissions)) %>% 
  arrange(desc(mean_kids))

```


```{r}
total_mean_kids_quarters <- admin_hb_speciality %>% 
  #select(year_enter, month_enter,quarters,quarters, number_admissions,specialty,healthboard) %>% 
mutate(quarters = as.yearqtr(week_ending))%>% 
  group_by(hb, quarters) %>% 
  #filter(year_enter == '2022') %>% 
  filter(specialty %in% c('Paediatrics (medical & surgical)','Paediatrics (medical)')) %>% 
  #filter(quarters == "Q4") %>% 
  #filter(healthboard == "NHS Greater Glasgow and Clyde" ) %>% 
  #filter(healthboard != 'Scotland') %>%
  summarise(mean_kids = mean(number_admissions)) %>% 
  arrange(desc(mean_kids))


total_mean_kids_quarters
```
```{r}
#NO TO USE , SCOTLAND MAKES A BIG DIFFERENCE



total_mean_kids_quarters %>% 
ggplot(aes(x= quarters , y = mean_kids, colour = hb))+
  
  geom_line()

  
```


```{r}
#three years without scotland

total_mean_kids_quarters_no_scotland<- admin_hb_speciality %>% 
  #select(year_enter, month_enter,quarters,quarters, number_admissions,specialty,healthboard) %>% 
mutate(quarters = yearquarter(week_ending))%>% # yearquarter() is a function from tsibli
  group_by(hb, quarters) %>% 
  #filter(year_enter == '2022') %>% 
  filter(specialty %in% c('Paediatrics (medical & surgical)','Paediatrics (medical)')) %>% 
  #filter(quarters == "Q4") %>% 
  #filter(healthboard == "NHS Greater Glasgow and Clyde" ) %>% 
  filter(hb!= 'Scotland') %>%
  summarise(mean_kids = mean(number_admissions)) %>% 
  arrange(desc(mean_kids))


total_mean_kids_quarters_no_scotland
```

```{r}
total_mean_kids_quarters_no_scotland %>% 
ggplot(aes(x= quarters , y = mean_kids, colour = hb))+
  geom_line()+
  labs(
    title = "Kids Number Admission by Quarters/Healthboard",
    x = "Quarters",
    y = "Admission Numbers"
  )
```
```{r}
total_mean_kids_quarters_no_scotland %>% 
ggplot(aes(x= quarters , y = mean_kids, colour = hb))+
  geom_line()+
  facet_wrap(~hb)+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  labs(
    title = "Kids Number Admission by Quarters",
    x = "Quarters",
    y = "Admission Numbers"
  )
```

```{r}
# Add line lockdown
total_mean_kids_quarters_no_scotland %>% 
ggplot(aes(x= quarters , y = mean_kids, colour = hb))+
  geom_line()+
  labs(
    title = "Kids Number Admission by Quarters/Healthboard",
    x = "Quarters",
    y = "Admission Numbers"
  )+
 geom_vline(xintercept = as.numeric(as.Date (yearquarter("2020 Q2"))),col ="firebrick", lwd = 0.05)+
  annotate("text", x= as.numeric(as.Date (yearquarter("2020 Q2"))), y= 175, label="COVID Lockdown", angle=90, size=5, color="blue") +
  geom_vline(xintercept =as.numeric(as.Date(yearquarter("2022 Q2"))),col ="firebrick", lwd = 0.05)+
  annotate("text", x= as.numeric(as.Date (yearquarter("2022 Q2"))), y= 180, label="summer", angle=90, size=5, color="blue")
  
```











```{r}
total_mean_kids_quarters_no_scotland %>% 
ggplot(aes(x= quarters , fill = hb))+
  geom_histogram()
```





```{r}
total_mean_kids_quarters_no_scotland %>% 
ggplot(aes(x= quarters , fill = mean_kids))+
  geom_histogram()+
facet_wrap(quarters ~ healthboard)
```





```{r}
total_mean_kids_quarters_no_scotland %>% 
ggplot(aes(x= quarters , y = mean_kids, colour = healthboard))+
  geom_line()
```

