---
title: "R Notebook"
output: html_notebook
---


```{r}
deprivation <- read_csv("raw_data/deprivation.csv")
```

```{r}
deprivation <- deprivation %>% 
  select(!ends_with("QF"))
```

```{r}
deprivation

shb <- read_csv("raw_data/deprivation_data/deprivation_sb.csv")

shb

```

```{r}
deprivation_joined <- left_join(deprivation, shb, by = c("HB" = "SHB")) %>% clean_names()

deprivation

dep_joined_2 <- deprivation %>% 
  mutate(HB = recode(HB,
                     "S08000015" = "NHS Ayrshire and Arran",
                     "S08000016" = "NHS Borders",
                     "S08000017" = "NHS Dumfries and Galloway",
                     "S08000019" = "NHS Forth Valley",
                     "S08000020" = "NHS Grampian",
                     "S08000022" = "NHS Highland",
                     "S08000024" = "NHS Lothian",
                     "S08000025" = "NHS Orkney",
                     "S08000026" = "NHS Shetland",
                     "S08000028" = "NHS Western Isles",
                     "S08000029" = "NHS Fife",
                     "S08000030" = "NHS Tayside",
                     "S08000031" = "NHS Greater Glasgow and Clyde",
                     "S08000032" = "NHS Lanarkshire",
                     "SB0801" = "The Golden Jubliee National Hospital",
                     "SN0811" = "National Facility Louisa Jordan")) %>% 
  clean_names()

dep_joined_2
```

```{r}
deprivation_joined <- deprivation_joined %>% 
  select(id_x, quarter, shb_name, admission_type:average_length_of_stay) %>% 
  rename("id" = "id_x")
```

```{r}
deprivation_joined %>% 
  drop_na() %>% 
  group_by(simd) %>% 
  summarise(avg_length_stay = mean(average_length_of_stay))
```

```{r}
deprivation_joined %>% 
  drop_na() %>% 
  filter(admission_type != "All Day cases") %>% 
  group_by(quarter, admission_type) %>% 
  summarise(avg_length_stay = mean(average_length_of_stay)) %>% 
  ggplot(aes(quarter, avg_length_stay, group = admission_type, colour = admission_type)) +
  geom_line() +
  theme(axis.text.x = element_text(face="bold", 
                           size=8, angle=45)) 

```

```{r}
deprivation_joined %>% 
  drop_na() %>% 
  mutate(simd = as.character(simd)) %>% 
  group_by(quarter, simd) %>% 
  summarise(avg_length_stay = mean(average_length_of_stay)) %>% 
  ggplot(aes(quarter, avg_length_stay, group = simd, colour = simd)) +
  geom_line() +
  theme(axis.text.x = element_text(face="bold", 
                           size=8, angle=45)) 

# the more deprived you are the greater your stay length
# when covid hit, the most deprived people the highest stay length on average
```

```{r}
# what does the data look like for quarter 1 and 4 only?

## can put this stuff into timeseries plots

deprivation_joined %>% 
  drop_na() %>% 
  mutate(simd = as.character(simd)) %>% 
  filter(str_detect(quarter, "Q[1|4]")) %>% 
  group_by(quarter, simd) %>% 
  summarise(avg_length_stay = mean(average_length_of_stay)) %>% 
  ggplot(aes(quarter, avg_length_stay, group = simd)) +
  geom_line() +
  theme(axis.text.x = element_text(face="bold", 
                           size=8, angle=45)) +
  facet_wrap(~simd)
```

```{r}
dep_joined_2 %>% 
  
  


  
```

